### ISSUE TITLE
Changing a playing stream might throw NPE

### ISSUE THREAD

**Issue by ciuc** [ciuc/InternetRadioClock#11]
```
radioclock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.NullPointerException
                                                                           at ro.antiprotv.radioclock.ClockActivity.lightButton(ClockActivity.java:294)
                                                                           at ro.antiprotv.radioclock.ClockActivity.access$1400(ClockActivity.java:52)
                                                                           at ro.antiprotv.radioclock.ClockActivity$CustomOnPreparedListener.onPrepared(ClockActivity.java:320)
                                                                           at com.devbrackets.android.exomedia.core.EMListenerMux.performPreparedHandlerNotification(EMListenerMux.java:259)
                                                                           at com.devbrackets.android.exomedia.core.EMListenerMux.access$000(EMListenerMux.java:41)
                                                                           at com.devbrackets.android.exomedia.core.EMListenerMux$1.run(EMListenerMux.java:250)
                                                                           at android.os.Handler.handleCallback(Handler.java:725)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                           at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ciuc** [comment]
This is b/c when the playing stream is eq to the one we just changed, the player is stopped, which nullifies the clicked button => NPE
